spring.data.mongodb.uri=${MONGO_URI}
server.port=${PORT:8080}
razorpay.key.id=${RAZORPAY_KEY_ID}
razorpay.key.secret=${RAZORPAY_KEY_SECRET}
server.servlet.context-path=/api/v1.0
spring.data.mongodb.auto-index-creation=true
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.security.servlet.UserDetailsServiceAutoConfiguration
clerk.issuer=https://superb-tapir-67.clerk.accounts.dev
clerk.jwks-url=https://superb-tapir-67.clerk.accounts.dev/.well-known/jwks.json
clerk.webhook.secret=whsec_jRm9L9c/sjWMBmkDFXd9wusa/z3tPEqU
#file upload configuration
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=25MB
spring.servlet.multipart.max-request-size=25MB

